import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[shell]
program = "/home/linuxbrew/.linuxbrew/bin/tmux"
args = ["new-session", "-A", "-s", "general"]

[env]
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"
TERM = "xterm-256color"

[font]
size = 11.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]
